package springapp.web.model;
// Generated Feb 24, 2015 9:42:12 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeNumber;
     private int idEmployee;
     private String lastName;
     private String firstName;
     private long ssn;
     private String payRate;
     private Integer payRatesId;
     private Integer vacationDays;
     private Byte paidToDate;
     private Byte paidLastYear;

    public Employee() {
    }

    public Employee(int employeeNumber, int idEmployee, String lastName, String firstName, long ssn) {
        this.employeeNumber = employeeNumber;
        this.idEmployee = idEmployee;
        this.lastName = lastName;
        this.firstName = firstName;
        this.ssn = ssn;
    }
    public Employee(int employeeNumber, int idEmployee, String lastName, String firstName, long ssn, String payRate, Integer payRatesId, Integer vacationDays, Byte paidToDate, Byte paidLastYear) {
       this.employeeNumber = employeeNumber;
       this.idEmployee = idEmployee;
       this.lastName = lastName;
       this.firstName = firstName;
       this.ssn = ssn;
       this.payRate = payRate;
       this.payRatesId = payRatesId;
       this.vacationDays = vacationDays;
       this.paidToDate = paidToDate;
       this.paidLastYear = paidLastYear;
    }
   
    public int getEmployeeNumber() {
        return this.employeeNumber;
    }
    
    public void setEmployeeNumber(int employeeNumber) {
        this.employeeNumber = employeeNumber;
    }
    public int getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(int idEmployee) {
        this.idEmployee = idEmployee;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public long getSsn() {
        return this.ssn;
    }
    
    public void setSsn(long ssn) {
        this.ssn = ssn;
    }
    public String getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(String payRate) {
        this.payRate = payRate;
    }
    public Integer getPayRatesId() {
        return this.payRatesId;
    }
    
    public void setPayRatesId(Integer payRatesId) {
        this.payRatesId = payRatesId;
    }
    public Integer getVacationDays() {
        return this.vacationDays;
    }
    
    public void setVacationDays(Integer vacationDays) {
        this.vacationDays = vacationDays;
    }
    public Byte getPaidToDate() {
        return this.paidToDate;
    }
    
    public void setPaidToDate(Byte paidToDate) {
        this.paidToDate = paidToDate;
    }
    public Byte getPaidLastYear() {
        return this.paidLastYear;
    }
    
    public void setPaidLastYear(Byte paidLastYear) {
        this.paidLastYear = paidLastYear;
    }




}


