//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public decimal Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Zip { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Social_Security_Number { get; set; }
        public string Drivers_License { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<bool> Gender { get; set; }
        public bool Shareholder_Status { get; set; }
        public Nullable<decimal> Benefit_Plans { get; set; }
        public string Ethnicity { get; set; }
    }
}
